
import type { FlowStep } from '../types';
import { FlowStepType } from '../types';

// This file is auto-generated by scripts/generateFlowData.js
// Do not edit this file directly. Instead, edit flow.csv and run the script.

export const flowData: Record<string, FlowStep> = {
  "1A": {
    "id": "1A",
    "type": FlowStepType.Question,
    "text": "This is question step 1A.",
    "yesNextId": "1C",
    "noNextId": "1B"
  },
  "1C": {
    "id": "1C",
    "type": FlowStepType.Info,
    "text": "This is info step 1C.",
    "continueId": "2A"
  },
  "1B": {
    "id": "1B",
    "type": FlowStepType.Info,
    "text": "This is info step 1B.",
    "continueId": "2A"
  },
  "2A": {
    "id": "2A",
    "type": FlowStepType.Question,
    "text": "This is question step 2A.",
    "yesNextId": "2C",
    "noNextId": "2B"
  },
  "2C": {
    "id": "2C",
    "type": FlowStepType.Info,
    "text": "This is info step 2C.",
    "continueId": "3A"
  },
  "2B": {
    "id": "2B",
    "type": FlowStepType.Info,
    "text": "This is info step 2B.",
    "continueId": "3A"
  },
  "3A": {
    "id": "3A",
    "type": FlowStepType.Question,
    "text": "This is question step 3A.",
    "yesNextId": "3C",
    "noNextId": "3B"
  },
  "3C": {
    "id": "3C",
    "type": FlowStepType.Info,
    "text": "This is info step 3C.",
    "continueId": "4A"
  },
  "3B": {
    "id": "3B",
    "type": FlowStepType.Info,
    "text": "This is info step 3B.",
    "continueId": "4A"
  },
  "4A": {
    "id": "4A",
    "type": FlowStepType.Question,
    "text": "This is question step 4A.",
    "yesNextId": "4C",
    "noNextId": "4B"
  },
  "4C": {
    "id": "4C",
    "type": FlowStepType.Info,
    "text": "This is info step 4C.",
    "continueId": "5A"
  },
  "4B": {
    "id": "4B",
    "type": FlowStepType.Info,
    "text": "This is info step 4B.",
    "continueId": "5A"
  },
  "5A": {
    "id": "5A",
    "type": FlowStepType.Question,
    "text": "This is question step 5A.",
    "yesNextId": "5C",
    "noNextId": "5B"
  },
  "5C": {
    "id": "5C",
    "type": FlowStepType.End,
    "text": "This is the end of the flow at step 5C.",
    "actionResult": "Result for 5C"
  },
  "5B": {
    "id": "5B",
    "type": FlowStepType.Question,
    "text": "This is question step 5B.",
    "yesNextId": "5E",
    "noNextId": "5D"
  },
  "5E": {
    "id": "5E",
    "type": FlowStepType.End,
    "text": "This is the end of the flow at step 5E.",
    "actionResult": "Result for 5E"
  },
  "5D": {
    "id": "5D",
    "type": FlowStepType.Question,
    "text": "This is question step 5D.",
    "yesNextId": "5G",
    "noNextId": "5F"
  },
  "5G": {
    "id": "5G",
    "type": FlowStepType.End,
    "text": "This is the end of the flow at step 5G.",
    "actionResult": "Result for 5G"
  },
  "5F": {
    "id": "5F",
    "type": FlowStepType.End,
    "text": "This is the end of the flow at step 5F.",
    "actionResult": "Result for 5F"
  }
};
