import type { Outcome } from '../types';

// This file is auto-generated by scripts/generateData.js
// Do not edit this file directly. Instead, edit outcomes.csv and run the script.

export const outcomes: Record<string, Outcome> = {
  "OUTCOME_5C": {
    "id": "OUTCOME_5C",
    "title": "Final Result: Conclusion 5C",
    "description": "This is the detailed explanation for outcome 5C. You reached this conclusion because you made a specific series of choices leading here."
  },
  "OUTCOME_5E": {
    "id": "OUTCOME_5E",
    "title": "Final Result: Conclusion 5E",
    "description": "This is the detailed explanation for outcome 5E. You followed the path that led to this specific result based on your answers."
  },
  "OUTCOME_5G": {
    "id": "OUTCOME_5G",
    "title": "Final Result: Conclusion 5G",
    "description": "This is the detailed explanation for outcome 5G. This is the result of navigating the decision tree in a particular way."
  },
  "OUTCOME_5F": {
    "id": "OUTCOME_5F",
    "title": "Final Result: Conclusion 5F",
    "description": "Your answers to the questions have led you to this final recommendation."
  }
};
